### ISSUE TITLE
Add link to prelude or other listing

### ISSUE THREAD

**Issue by yehoshuapw** [divarvel/haskle#10]
Thanks, this is lots of fun - and instructive.

one of the issue's I've had, is not knowing sometimes which function is in the prelude or not,
maybe adding a link to [hackage Prelude](https://hackage.haskell.org/package/base-4.16.1.0/docs/Prelude.html) can help.

(or probably better, a page with the list of all the functions by name only.)

and maybe, after solving a link to the right function, like [readFile](https://hackage.haskell.org/package/base-4.16.1.0/docs/Prelude.html#v:readFile) :: FilePath -> IO String

**Comment by divarvel** [comment]
Oh that's a great idea! I'll check how I can make it fit in the current design.

**Comment by divarvel** [comment]
(adding a link to the `Prelude` module is the easy part. Adding links to each function is a bit harder (at least for the symbolic functions)

**Comment by yehoshuapw** [comment]
> the symbolic functions

I'm not sure about this, but [<*>](https://hackage.haskell.org/package/base-4.16.1.0/docs/Prelude.html#v:-60--42--62-) is just using the ASCII, with dashes before and after - and I think the rest are too.

**Comment by divarvel** [comment]
This should be handled by https://github.com/divarvel/haskle/commit/e79e0434d78412c5ba492b348043945efc0f0e47 (yes the haddock encoding is `"-" <> ord c <> "-"`)
