### ISSUE TITLE
Tuple as a '*->*->*' kind

### ISSUE THREAD

**Issue by yehoshuapw** [divarvel/haskle#11]
this might complicate things, but is worth bringing up as an idea:
maybe types like (a,b) should be Tuple a b, and then end up as '? ? ?' in the problem.

**Comment by divarvel** [comment]
I have done this for lists already (they appear as `List a` instead of `[a]`). Doing so with tuples could be interesting. Idk if it would make things too hard :thinking: 

In any case, I won't do it for `->` ^^

**Comment by divarvel** [comment]
If you want to have a try, you only need to change the signatures at the end of Main.elm to see how it would look like.
