### ISSUE TITLE
Gradually reveal the function name when the type is completely revealed

### ISSUE THREAD

**Issue by divarvel** [divarvel/haskle#4]
Some functions like `cos`, `tan`, etc have a relatively uninformative type, and as such are hard to find when they come up.

**Comment by yehoshuapw** [comment]
another option is (when there's many of the same type of function) to treat them all as the same.
(Also, I think you closed this issue in ee1ba893d9d0921c7c9a7ea6bf7bf6d02cc83439 (really sometime before))

**Comment by divarvel** [comment]
yes, i forgot to close the issue when pushing the code.
